import bdt from './pieces/Chess_bdt60.png';
import blt from './pieces/Chess_blt60.png';
import rdt from './pieces/Chess_rdt60.png';
import rlt from './pieces/Chess_rlt60.png';
import kdt from './pieces/Chess_kdt60.png';
import klt from './pieces/Chess_klt60.png';
import qdt from './pieces/Chess_qdt60.png';
import qlt from './pieces/Chess_qlt60.png';
import ndt from './pieces/Chess_ndt60.png';
import nlt from './pieces/Chess_nlt60.png';
import pdt from './pieces/Chess_pdt60.png';
import plt from './pieces/Chess_plt60.png';
import {Queen,King,Pawn,Knight,Bishop,Rook} from './util';

export const initialPositionsWhite = {
    '0+0' : new Rook('black0rook',rdt),
    '0+1' : new Knight('black0knight',ndt),
    '0+2' : new Bishop('black0bishop',bdt),
    '0+3' : new Queen('black0queen',qdt),
    '0+4' : new King('black0king',kdt),
    '0+5' : new Bishop('black1bishop',bdt),
    '0+6' : new Knight('black1knight',ndt),
    '0+7' : new Rook('black1rook',rdt),
    '1+0' : new Pawn('black0pawn',pdt),
    '1+1' : new Pawn('black1pawn',pdt),
    '1+2' : new Pawn('black2pawn',pdt),
    '1+3' : new Pawn('black3pawn',pdt),
    '1+4' : new Pawn('black4pawn',pdt),
    '1+5' : new Pawn('black5pawn',pdt),
    '1+6' : new Pawn('black6pawn',pdt),
    '1+7' : new Pawn('black7pawn',pdt),
    '6+0' : new Pawn('white0pawn',plt),
    '6+1' : new Pawn('white1pawn',plt),
    '6+2' : new Pawn('white2pawn',plt),
    '6+3' : new Pawn('white3pawn',plt),
    '6+4' : new Pawn('white4pawn',plt),
    '6+5' : new Pawn('white5pawn',plt),
    '6+6' : new Pawn('white6pawn',plt),
    '6+7' : new Pawn('white7pawn',plt),
    '7+0' : new Rook('white0rook',rlt),
    '7+1' : new Knight('white0knight',nlt),
    '7+2' : new Bishop('white0bishop',blt),
    '7+3' : new Queen('white0queen',qlt),
    '7+4' : new King('white0king',klt),
    '7+5' : new Bishop('white1bishop',blt),
    '7+6' : new Knight('white1knight',nlt),
    '7+7' : new Rook('white1rook',rlt)
}

export const initialPositionsBlack = {
    '0+0' : new Rook('white0rook',rlt),
    '0+1' : new Knight('white0knight',nlt),
    '0+2' : new Bishop('white0bishop',blt),
    '0+3' : new Queen('white0queen',qlt),
    '0+4' : new King('white0king',klt),
    '0+5' : new Bishop('white1bishop',blt),
    '0+6' : new Knight('white1knight',nlt),
    '0+7' : new Rook('white1rook',rlt),
    '1+0' : new Pawn('white0pawn',plt),
    '1+1' : new Pawn('white1pawn',plt),
    '1+2' : new Pawn('white2pawn',plt),
    '1+3' : new Pawn('white3pawn',plt),
    '1+4' : new Pawn('white4pawn',plt),
    '1+5' : new Pawn('white5pawn',plt),
    '1+6' : new Pawn('white6pawn',plt),
    '1+7' : new Pawn('white7pawn',plt),
    '6+0' : new Pawn('black0pawn',pdt),
    '6+1' : new Pawn('black1pawn',pdt),
    '6+2' : new Pawn('black2pawn',pdt),
    '6+3' : new Pawn('black3pawn',pdt),
    '6+4' : new Pawn('black4pawn',pdt),
    '6+5' : new Pawn('black5pawn',pdt),
    '6+6' : new Pawn('black6pawn',pdt),
    '6+7' : new Pawn('black7pawn',pdt),
    '7+0' : new Rook('black0rook',rdt),
    '7+1' : new Knight('black0knight',ndt),
    '7+2' : new Bishop('black0bishop',bdt),
    '7+3' : new Queen('black0queen',qdt),
    '7+4' : new King('black0king',kdt),
    '7+5' : new Bishop('black1bishop',bdt),
    '7+6' : new Knight('black1knight',ndt),
    '7+7' : new Rook('black1rook',rdt)
}
